### ISSUE TITLE
feature request: tags (labels)

### ISSUE THREAD

**Issue by tzwaeaen** [dh1011/subscription-manager#16]
Hello,

would it be possible to add tags that you can add to the subscriptions to get an overview on amount spent per tag per period?

**Comment by dh1011** [comment]
Good idea! I am working on porting this app to Next.js so that the front end and back end can be included in a single Docker image. I can include this feature in the new build.

**Comment by aadilxgit** [comment]
> Good idea! I am working on porting this app to Next.js so that the front end and back end can be included in a single Docker image. I can include this feature in the new build.

Any update on this?

**Comment by dh1011** [comment]
I finally have time to work on this. I’ve pushed the image to `dh1011/subscription-manager:3.0.0`, which uses Next.js for both the front end and back end, and includes the tagging features.

**Comment by littlecorsican** [comment]
> dh1011/subscription-manager:3.0.0

you are using nextjs now? but in the repo i am still seeing react

**Comment by jrg09** [comment]
Hi! Awesome job! It works really nice, one question, to use dh1011/subscription-manager:3.0.0, it need to be edited on docker-compose.yml file, is it right?

**Comment by dh1011** [comment]
Hi @jrg09  thanks for using the project! Yes, your `docker-compose.yml` should look like this:

```yaml
version: "3.9"
services:
  app:
    image: dh1011/subscription-manager:3.0.0
    ports:
      - "3000:3000"
    volumes:
      - ./data:/app/data
    restart: unless-stopped
```
